#!/usr/bin/env bash
set -euo pipefail
: "${TARGET:?TARGET não definido}"
: "${SYSROOT:?SYSROOT não definido}"
: "${CONFIGURE_EXTRAS:=}"
CONFIGURE_EXTRAS+=" --prefix=/usr --with-sysroot=${SYSROOT} --target=${TARGET}"
CONFIGURE_EXTRAS+=" --enable-languages=c,c++ --disable-multilib --disable-nls --disable-werror"
# Agora já existem headers/stubs e a glibc no SYSROOT.
export CONFIGURE_EXTRAS
