#!/usr/bin/env bash
# hook: pre_build para ncurses
# Configuração clássica: widec, shared, terminfo em /usr.

set -eu

: "${ADM_INSTALL_ROOT:=/}"
: "${ADM_BUILD_SRC_DIR:?}"
: "${ADM_BUILD_BUILD_DIR:?}"

mkdir -p "$ADM_BUILD_BUILD_DIR"

export ADM_BUILD_PREFIX="${ADM_INSTALL_ROOT}/usr"

export ADM_BUILD_CONFIGURE_EXTRA="
  --with-shared
  --with-termlib
  --without-debug
  --enable-widec
  --enable-pc-files
  --with-pkg-config-libdir=/usr/lib/pkgconfig
  --mandir=/usr/share/man
  --with-manpage-format=gzip
  --with-manpage-colors
"

export CFLAGS="${CFLAGS:--O2 -pipe}"
export CXXFLAGS="${CXXFLAGS:--O2 -pipe}"
