#!/usr/bin/env bash
# hook: pre_build para gawk

set -eu

: "${ADM_INSTALL_ROOT:=/}"
: "${ADM_BUILD_SRC_DIR:?}"
: "${ADM_BUILD_BUILD_DIR:?}"

mkdir -p "$ADM_BUILD_BUILD_DIR"

export ADM_BUILD_PREFIX="${ADM_INSTALL_ROOT}/usr"

export ADM_BUILD_CONFIGURE_EXTRA="
  --prefix=/usr
  --sysconfdir=/etc
  --disable-static
  --enable-nls
  --docdir=/usr/share/doc/gawk-5.3.0
"

export CFLAGS="${CFLAGS:--O2 -pipe}"
export CXXFLAGS="${CXXFLAGS:--O2 -pipe}"
