#!/usr/bin/env bash
# hook: pre_build para mpc

set -eu

: "${ADM_INSTALL_ROOT:=/}"
: "${ADM_BUILD_SRC_DIR:?}"
: "${ADM_BUILD_BUILD_DIR:?}"

mkdir -p "$ADM_BUILD_BUILD_DIR"

export ADM_BUILD_PREFIX="${ADM_INSTALL_ROOT}/usr"

export ADM_BUILD_CONFIGURE_EXTRA="
  --prefix=/usr
  --enable-shared
  --disable-static
  --with-gmp=/usr
  --with-mpfr=/usr
"

export CFLAGS="${CFLAGS:--O2 -pipe}"
export CXXFLAGS="${CXXFLAGS:--O2 -pipe}"
