#!/usr/bin/env bash
# Hook genérico MESON - pre-configure
set -Eeuo pipefail
: "${ADM_WORK_DIR:?}" "${ADM_BUILD_DIR:?}"
cd "$ADM_WORK_DIR"
mkdir -p "$ADM_BUILD_DIR"
meson setup "$ADM_BUILD_DIR" --prefix=/usr --buildtype=release
