#!/usr/bin/env bash
set -Eeuo pipefail
: "${ADM_WORK_DIR:?}" "${ADM_BUILD_DIR:?}"
mkdir -p "$ADM_BUILD_DIR"
cd "$ADM_BUILD_DIR"
cmake -S "$ADM_WORK_DIR" -B "$ADM_BUILD_DIR" \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_BUILD_TYPE=Release
