#!/usr/bin/env bash
set -e
echo "[stage0 pre-build] preparando GCC Pass 1 (bootstrap)..."

# Descompactar dependências embutidas
tar -xf ../mpfr-4.2.2.tar.xz && mv -v mpfr-4.2.2 mpfr
tar -xf ../gmp-6.3.0.tar.xz && mv -v gmp-6.3.0 gmp
tar -xf ../mpc-1.3.1.tar.gz && mv -v mpc-1.3.1 mpc

# Corrigir libdir em hosts x86_64
case $(uname -m) in
  x86_64) sed -e '/m64=/s/lib64/lib/' -i gcc/config/i386/t-linux64 ;;
esac

mkdir -v build && cd build
echo "[stage0 pre-build] ambiente pronto para GCC Pass 1."
