#!/usr/bin/env bash
# hook: pre_build para util-linux (stage temporário em chroot)
# Cortando dependências extras (python, systemd, etc) pra ficar enxuto.

set -eu

: "${ADM_INSTALL_ROOT:=/}"
: "${ADM_BUILD_SRC_DIR:?}"
: "${ADM_BUILD_BUILD_DIR:?}"

mkdir -p "$ADM_BUILD_BUILD_DIR"

export ADM_BUILD_PREFIX="${ADM_INSTALL_ROOT}/usr"

# Versão 2.41.1 (metafile)
export ADM_BUILD_CONFIGURE_EXTRA="
  --disable-static
  --enable-shared
  --without-python
  --without-systemd
  --without-systemdsystemunitdir
  --disable-chfn-chsh
  --disable-login
  --disable-su
  --disable-runuser
  --without-udev
"

export CFLAGS="${CFLAGS:--O2 -pipe}"
export CXXFLAGS="${CXXFLAGS:--O2 -pipe}"
