#!/usr/bin/env bash
set -Eeuo pipefail
: "${ADM_WORK_DIR:?}" "${ADM_BUILD_DIR:?}"
cd "$ADM_WORK_DIR"; mkdir -p "$ADM_BUILD_DIR"; cd "$ADM_BUILD_DIR"

conf=(
  --prefix=/usr
  --with-system-zlib
  --disable-nls
  --disable-werror
  --enable-gold=no
  --enable-ld=default
  --enable-plugins
)
"$ADM_WORK_DIR/configure" "${conf[@]}"
