#!/usr/bin/env bash
set -Eeuo pipefail
: "${ADM_WORK_DIR:?}" "${ADM_BUILD_DIR:?}"

cd "$ADM_WORK_DIR"; mkdir -p "$ADM_BUILD_DIR"; cd "$ADM_BUILD_DIR"

BUILD_TRIPLET="${BUILD_TRIPLET:-$(gcc -dumpmachine || echo "$(uname -m)-pc-linux-gnu")}"
HOST_TRIPLET="${HOST_TRIPLET:-$BUILD_TRIPLET}"

export CC="${HOST_TRIPLET}-gcc"
export CXX="${HOST_TRIPLET}-g++"
export AR="${HOST_TRIPLET}-ar"
export RANLIB="${HOST_TRIPLET}-ranlib"

conf=(
  --prefix=/usr
  --build="$BUILD_TRIPLET"
  --host="$HOST_TRIPLET"
  --disable-werror
  --with-headers=/usr/include
)
"$ADM_WORK_DIR/configure" "${conf[@]}"
